#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

my $event = 'nethserver-rspamd-update';
event_actions ( $event, 'initialize-default-databases' => '00');

event_templates($event, qw(
    /etc/httpd/admin-conf.d/rspamd.conf
    /etc/postfix/main.cf
    /etc/rspamd/local.d/antivirus.conf
    /etc/rspamd/local.d/greylist.conf
    /etc/rspamd/local.d/history_redis.conf
    /etc/rspamd/local.d/ip_score.conf
    /etc/rspamd/local.d/metrics.conf
    /etc/rspamd/local.d/mx_check.conf
    /etc/rspamd/local.d/redis.conf
    /etc/rspamd/local.d/statistic.conf
    /etc/rspamd/local.d/surbl.conf
    /etc/rspamd/local.d/url_redirector.conf
    /etc/rspamd/local.d/worker-proxy.inc
    /etc/rspamd/local.d/worker-controller.inc
    /etc/rspamd/local.d/worker-normal.inc
    /etc/rspamd/local.d/fann_redis.conf
    /etc/rspamd/rspamd.conf.local
    /var/lib/nethserver/sieve-scripts/before.sieve
));

event_services($event, qw(
    rspamd restart
    postfix reload
    httpd-admin reload
    httpd reload
));

my $event = 'nethserver-rspamd-save';

event_actions($event, qw(
    firewall-adjust 91
));

event_templates($event, qw(
    /etc/httpd/admin-conf.d/rspamd.conf
    /etc/postfix/main.cf
    /etc/rspamd/local.d/antivirus.conf
    /etc/rspamd/local.d/greylist.conf
    /etc/rspamd/local.d/history_redis.conf
    /etc/rspamd/local.d/ip_score.conf
    /etc/rspamd/local.d/metrics.conf
    /etc/rspamd/local.d/mx_check.conf
    /etc/rspamd/local.d/redis.conf
    /etc/rspamd/local.d/statistic.conf
    /etc/rspamd/local.d/surbl.conf
    /etc/rspamd/local.d/url_redirector.conf
    /etc/rspamd/local.d/worker-proxy.inc
    /etc/rspamd/local.d/worker-controller.inc
    /etc/rspamd/local.d/worker-normal.inc
    /etc/rspamd/local.d/fann_redis.conf
    /etc/rspamd/rspamd.conf.local
    /var/lib/nethserver/sieve-scripts/before.sieve
));

event_services($event, qw(
    rspamd reload
    postfix reload
    httpd reload
    httpd-admin reload
));
