#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

my @templates = qw (
    /etc/clamd.d/rspamd.conf
    /etc/httpd/admin-conf.d/rspamd.conf
    /etc/postfix/main.cf
    /etc/rspamd/local.d/antivirus.conf
    /etc/rspamd/local.d/greylist.conf
    /etc/rspamd/local.d/history_redis.conf
    /etc/rspamd/local.d/ip_score.conf
    /etc/rspamd/local.d/metrics.conf
    /etc/rspamd/local.d/mx_check.conf
    /etc/rspamd/local.d/redis.conf
    /etc/rspamd/local.d/statistic.conf
    /etc/rspamd/local.d/surbl.conf
    /etc/rspamd/local.d/url_redirector.conf
    /etc/rspamd/local.d/worker-proxy.inc
    /etc/rspamd/local.d/worker-controller.inc
    /etc/rspamd/local.d/worker-normal.inc
    /etc/rspamd/local.d/worker-fuzzy.inc
    /etc/rspamd/local.d/fann_redis.conf
    /etc/rspamd/local.d/options.inc
    /etc/rspamd/local.d/multimap.conf
    /etc/rspamd/rspamd.conf.local
    /var/lib/nethserver/sieve-scripts/before.sieve
    /etc/rspamd/local_wl_from.map
    /etc/rspamd/local_wl_from_domains.map
    /etc/rspamd/local_bl_from.map
    /etc/rspamd/local_bl_from_domains.map
    /etc/rspamd/local_wl_to_domains.map
    /etc/rspamd/local_wl_to.map
    /etc/rspamd/local_forbidden_file_extension.map

);


my $event = 'nethserver-mail-filter-update';
event_actions ( $event, qw (
    initialize-default-databases 00
    nethserver-rspamd-daemon-reload 01
    nethserver-rspamd-unlink-modules-configuration 01
    nethserver-rspamd-disable-modules-configuration 10
    ));

event_templates($event, @templates);

event_services($event, qw(
    rspamd restart
    postfix reload
    httpd-admin reload
    httpd reload
));

$event = 'nethserver-mail-filter-save';

event_actions($event, qw(
    nethserver-rspamd-unlink-modules-configuration 01
    nethserver-rspamd-disable-modules-configuration 10
    firewall-adjust 91
));

event_templates($event, @templates); 

event_services($event, qw(
    rspamd reload
    postfix reload
    httpd reload
    httpd-admin reload
));
